import { Salsa } from "next/font/google";
import "./index.css";
import Navbar from "@/components/Navbar";

const salsa = Salsa({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={salsa.className}>
        {/* Navbar */}
        <Navbar/>

        <main className="max-container">{children}</main>

        {/* Footer */}
      </body>
    </html>
  );
}
